const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F1F5F9",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#E2E8F0",
    secondaryForeground: "#1E293B",
    muted: "#E2E8F0",
    mutedForeground: "#64748B",
    accent: "#EFF6FF",
    accentForeground: "#1D4ED8",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    ring: "#2563EB",
  },
  radius: 12,
};

export default colors;
